### PR TITLE
Fix issue with mounting /directory/ versus /directory

### PR DESCRIPTION
**Pull request by srguiwiz**
To fix issue #43

### CODE REVIEW

**Comment by srguiwiz** [comment]
The code is better than the commit message.

**Comment by srguiwiz** [comment]
@AdrienCastex , would be nice to have this part of official version, for automated builds without having to patch. Thx.

**Comment by srguiwiz** [comment]
@AdrienCastex , are you not sure of benefits of this fix for #43, not sure of correctness, or just busy?  You say and I'll try to address.

Want this fix to go onto npm as 2.4.2 so our build process can install it.  This fix was/is needed for our in-house Mac users using digest authentication.

Thank you so much for a very useful and usable library!

**Comment by AdrienCastex** [comment]
Hello,

I am very sorry for the wait, I've been very busy.

This is a very nice change, but I am not sure it will work in every case. I would propose the following: doing the test with the `/` and without. This way we cover all cases. What do you think ?

```typescript
this.userManager.getUserByName(authProps.username, (e, user) => {
    if(e)
        return onError(e);
        console.log('TRY');

    let ha1 = md5(`${authProps.username}:${this.realm}:${user.password ? user.password : ''}`);
    if(authProps.algorithm === 'MD5-sess')
        ha1 = md5(`${ha1}:${authProps.nonce}:${authProps.cnonce}`);
    
    let digestUri = authProps.uri || ctx.requested.uri;
    if(authProps.uri)
    { // Check for replay attacks

        let mismatch = false;
        if(authProps.uri.length > ctx.requested.uri)
        {
            mismatch = authProps.uri.length !== ctx.requested.uri + 1 || ctx.requested.uri.indexOf(authProps.uri) !== 0;
        }
        else if(authProps.uri.length < ctx.requested.uri)
        {
            mismatch = authProps.uri.length + 1 !== ctx.requested.uri || authProps.uri.indexOf(ctx.requested.uri) !== 0;
        }

        console.log('mismatch', mismatch, authProps.uri, ctx.requested.uri);
        if(mismatch)
            return onError(Errors.BadAuthentication);
    }

    // Remove ending / or \ characters in the uri
    const trimLastChars = [ '/', '\\' ];
    while(trimLastChars.some(char => char === digestUri[digestUri.length - 1]))
    {
        digestUri = digestUri.substring(0, digestUri.length - 1);
    }
    
    if(authProps.qop === 'auth-int')
        return onError(Errors.WrongHeaderFormat); 

    const produceDigest = (endingCharacter : string) => {
        const ha2 = md5(`${ctx.request.method.toString().toUpperCase()}:${digestUri}${endingCharacter}`);

        let result;
        if(authProps.qop === 'auth-int' || authProps.qop === 'auth')
            result = md5(`${ha1}:${authProps.nonce}:${authProps.nc}:${authProps.cnonce}:${authProps.qop}:${ha2}`);
        else
            result = md5(`${ha1}:${authProps.nonce}:${ha2}`);

        return result;
    }
    
    // Produce 3 versions, one without ending character, one with / and one with \\
    const results = [
        produceDigest(''),
        produceDigest('/'),
        produceDigest('\\')
    ];

    if(results.some((digest) => digest.toLowerCase() === authProps.response.toLowerCase()))
        callback(Errors.None, user);
    else
        onError(Errors.BadAuthentication);
});
```

**Comment by srguiwiz** [comment]
Additional info: Needed in at least some Firefox (fetch) and in Mac OS X mounting. In contrast, not needed in Chrome and in Windows mounting. Only some client softwares send requests this way. We have seen light use with all of those softwares in recent weeks, without fix to fail, with fix installed working.

I am thinking of correctness and computational effort.  Your fix should work.  But I feel the extra computational effort I would avoid.  Let me explain:

For failing digests, your version needs to compute three digests.  In addition to md5 that involves memory allocations for strings being made.

In complying cases mine immediately continues, after first comparison, which by nature of string storage should be a mere pointer comparison.  Yours I think is equally efficient in that case.

There is a difference of one versus two digest calculations when "the problem case" occurs.  Mine recognizes it early, and only needs one digest calculation.  Yours fails on first, then needs a second calculation.

Mine in non-complying cases, only if it "looks like the problem" then uses an already existing string, for a single digest effort.

In case of doubt, it feels more conservative to only allow in an additional narrowly defined exception, rather than a broader number of additional cases.  My version as submitted is quite conservative, it only allows minimally more.

Also, I think backslashes are not used as path separators in URLs, even coming from Windows.

For our needs I made a patch file we apply after install, that is why I am more relaxed about the timing now. But fixing this is a contribution to "better working stuff".

Let me say despite being critical in replying what I think, hoping I got it right, I do very much respect the fact you have put in the time and effort to make a complete working implementation.

**Comment by AdrienCastex** [comment]
You are right, lighter computation is better for authentication and backslashes shouldn't happen.

I guess, we can make the assumption that the digest sent by the client has been made with the value of the `uri` property in the authentication header (RFC compliant). So we can use by default `authProps.uri` instead of `ctx.requested.uri`.

We still need to limit the scope of the replay attacks, and to do so we need to check that the uri of the request and the uri of the header are the same (ignoring the ending slash if there is any).

This is the new implementation:
```typescript
this.userManager.getUserByName(authProps.username, (e, user) => {
    if(e)
        return onError(e);

    let ha1 = md5(`${authProps.username}:${this.realm}:${user.password ? user.password : ''}`);
    if(authProps.algorithm === 'MD5-sess')
        ha1 = md5(`${ha1}:${authProps.nonce}:${authProps.cnonce}`);
    
    /* New section */
    let digestUri = authProps.uri || ctx.requested.uri;
    if(digestUri !== ctx.requested.uri)
    {
        if(Math.abs(digestUri.length - authProps.uri.length) !== 1 || (digestUri.indexOf(ctx.requested.uri) !== 0 && ctx.requested.uri.indexOf(digestUri) !== 0))
        {
            return onError(Errors.BadAuthentication);
        }
    }
    /* End of new section */

    let ha2;
    if(authProps.qop === 'auth-int')
        return onError(Errors.WrongHeaderFormat); // ha2 = md5(ctx.request.method.toString().toUpperCase() + ':' + digestUri + ':' + md5(...));
    else
        ha2 = md5(`${ctx.request.method.toString().toUpperCase()}:${digestUri}`);

    let result;
    if(authProps.qop === 'auth-int' || authProps.qop === 'auth')
        result = md5(`${ha1}:${authProps.nonce}:${authProps.nc}:${authProps.cnonce}:${authProps.qop}:${ha2}`);
    else
        result = md5(`${ha1}:${authProps.nonce}:${ha2}`);

    if(result.toLowerCase() === authProps.response.toLowerCase())
        callback(Errors.None, user);
    else
        onError(Errors.BadAuthentication);
});
```

**Comment by srguiwiz** [comment]
Good catch, you are right, my earlier version would let pass another directory name of same length.

One point:  In reality only `ctx.requested.uri` is observed shorter than `authProps.uri`.  The other case, where `authProps.uri` is shorter than `ctx.requested.uri` has not been observed.  By strict "only fix what is broken" one could keep code shorter.  But it is okay to cover both.

As only `ctx.requested.uri` is observed shorter than `authProps.uri`, to avoid the cost of a second `indexOf` occurring, you may want to do the decisive test first, avoid the computation for the other. In your suggested code flip it to:

```
        if(Math.abs(digestUri.length - authProps.uri.length) !== 1 || (ctx.requested.uri.indexOf(digestUri) !== 0 && digestUri.indexOf(ctx.requested.uri) !== 0))
        {
            return onError(Errors.BadAuthentication);
        }
```

Hope the `indexOf` implementation returns `-1` quickly when seeing impossibility due to length.  The idea is avoiding the cost of preprocessing of [Boyer–Moore](https://en.wikipedia.org/wiki/Boyer%E2%80%93Moore_string-search_algorithm).

Which brings up a second point, cost of `indexOf`:  One must hope [startsWith](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith) is implemented lower cost than `indexOf`, as simpler comparison at one offset only.

One could [deal with availability](https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-packages-json) of `startsWith` only from Node 4 on with an entry in `package.json`

```
  "engines": {
    "node": ">=4.0.0"
  },
```

A quick way to tell whether `startsWith` is available could be in static code, once at module loading

```
var hasStartsWith = !!"".startsWith;
```

This reminded me you are authoring in TypeScript, which I normally don't do, so I should let you make your own choices in this / your project.

Note that those not configuring digest authentication still could run Node before 4.0.0 and would not notice.  Node 4 ended LTS maintenance status in 2018.

Also you could avoid two string comparisons with a `switch` statement on the length difference.

I admit, this may be a lot of discussion for a small issue.  After all, only use of digest authentication causes it.  Only directory requests cause it.  Directory requests are common, but only part of the traffic. 
 Only Mac directory mounting and Firefox users cause it.  Overall, not a lot of CPU use.  But, I happen to see it.

If you just want to release it as you wrote it above, or my latest change from today, which had three months burn-in, either is fine, go ahead.  It fixes a problem.  Thank you again.

**Comment by AdrienCastex** [comment]
My aim is not to get ride of the problem but to solve it the best way possible, so this whole discussion, even if it is a small piece of the program, is very interesting.

I believe it is preferable to extract the general case from a specific problem instead of just limiting the fix to the problem. That's why I prefer not to assume one URI cannot be bigger than the other one.

I guess the method `indexOf` is optimised and won't check for impossible cases (depending on the length), but let's not assume the implementation. I also found a better way to make a `startsWith` without a native implementation and without rewriting it:
```javascript
'my string'.lastIndexOf('my', 0) === 0
```

I think your idea of the switch case is a very good idea.

```typescript
const digestUri = authProps.uri || ctx.requested.uri;
if(digestUri !== ctx.requested.uri)
{
    let uriMismatch;

    switch(digestUri.length - authProps.uri.length)
    {
        case -1:
            uriMismatch = !startsWith(authProps.uri, digestUri);
            break;

        case 1:
            uriMismatch = !startsWith(digestUri, authProps.uri);
            break;

        default:
            uriMismatch = true;
            break;
    }

    if(uriMismatch)
    {
        return onError(Errors.BadAuthentication);
    }
}
```

And the static method which can be used elsewhere:
```typescript
export let startsWith : (str : string, strToFind : string) => boolean;

const hasStartsWith = (String.prototype as any).startsWith;
if(hasStartsWith)
{
    startsWith = function(str : string & { startsWith(strToFind : string) : boolean }, strToFind : string) : boolean
    {
        return str.startsWith(strToFind);
    }
}
else
{
    startsWith = function(str : string, strToFind : string) : boolean
    {
        return str.lastIndexOf(strToFind, 0) === 0;
    }
}
```

**Note:** this implementation is case sensitive.

If you have no more advise about it, I believe we achieved the best way to solve this, including the general case and the possible security flaw. I would add it to the next version `2.4.2`.

**Comment by srguiwiz** [comment]
Nice.

While I don't know how `lastIndexOf` exactly is implemented, it probably has same characteristics as or similar to `indexOf`. Therefore, might as well stick with `indexOf`, which in the successful case, hopefully most of the time, will find a match on first try, at 0.  `lastIndexOf` probably starts looking from the back towards the front.

Good to go.  Commit it.

This appears to be an example for:  Will people in the future be able to understand what it does?  And, how about the rule not to optimize too early?  If the balance between readability and better performance goes too far one way or the other, then it may overall become more expensive than somewhere in the middle.

One wisdom is:  Don't optimize if it doesn't show up in performance analysis.  But then again, ten thousand small pieces of code each running at half the speed, or at a tenth of the speed, none of them will show up, and they make it slower, together.  Which is worse then?  Big code requiring bigger memory chips and longer time to load, or slow code using many people's time and using more electricity?  Probably on the server bigger code is more acceptable, speed wins.

Also here to think:  How short or how long are the strings?  I see those `uri` are in fact paths, not the whole URI.  Could be long, could be short, depending on use, server installation, should make no assumptions.

Just so happened we switched authentication to a different layer.  Still using this good library, but do not foresee further exercising this very piece of authentication code as we have recent months.

I don't know how exactly and how much you test, but I suggest mounting a directory from a Mac should show the difference between without fix and with fix.

For correctness, a fix should go in, I think we agree.

**Comment by AdrienCastex** [comment]
I don't think too that `indexOf` and `lastIndexOf` are optimized for our case. Maybe a simple loop would be more appropriate ?

Thank you very much for your contribution and your wisdom.

**Comment by srguiwiz** [comment]
As only Node before 4.0.0 would hit the alternative to built-in `startsWith`, there is little or no impact if it is suboptimal, hence it is good as is. From Node 4.0.0 on, we hope `startsWith` does the simple loop natively.  Thank _you_ too.

**Pull request closed without merging**
